if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "INPUT and OUTPUT are required")
endif()
file(READ "${INPUT}" SPIRV_HEX HEX)
string(LENGTH "${SPIRV_HEX}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")
set(BODY "")
set(I 0)
while(I LESS HEX_LEN)
  string(SUBSTRING "${SPIRV_HEX}" ${I} 2 BYTE)
  string(APPEND BODY "0x${BYTE},")
  math(EXPR I "${I} + 2")
  math(EXPR INDEX "${I} / 2")
  math(EXPR MOD "${INDEX} % 16")
  if(MOD EQUAL 0)
    string(APPEND BODY "\n")
  endif()
endwhile()
file(WRITE "${OUTPUT}" "#pragma once\n#include <cstddef>\n#include <cstdint>\nnamespace truthraw::truthnegative_vulkan_dense::generated {\nalignas(4) inline constexpr unsigned char kDense4xSpirv[] = {\n${BODY}\n};\ninline constexpr std::size_t kDense4xSpirvBytes = sizeof(kDense4xSpirv);\n}\n")
message(STATUS "Embedded ${BYTE_COUNT} SPIR-V bytes into ${OUTPUT}")
